# Generated by Django 2.2.19 on 2024-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный адрес группы')),
                ('description', models.TextField(verbose_name='Описание сообщества')),
            ],
        ),
    ]
